/* Creative-discipline taxonomy for BareFolio.
   Organised under the five umbrella categories the platform covers, expanded
   from the most generic practice (e.g. "Graphic Design") to more specific ones
   (e.g. "Branding", "UX/UI Design"). Used by the onboarding "main discipline"
   picker: `SUGGESTED_DISCIPLINES` are surfaced as pills by default, while the
   full `DISCIPLINES` list backs the search box.

   English names — the platform UI is English. Keep every name unique so it can
   be used directly as a React key. */

export interface DisciplineCategory {
  category: string;
  disciplines: string[];
}

export const DISCIPLINE_CATEGORIES: DisciplineCategory[] = [
  {
    category: 'Fine Arts',
    disciplines: [
      'Painting',
      'Sculpture',
      'Drawing',
      'Printmaking',
      'Engraving',
      'Installation Art',
      'Digital Art',
      'Ceramics',
      'Collage',
      'Mixed Media',
      'Mural Art',
      'Street Art',
      'Graffiti',
      'Calligraphy',
      'Mosaic',
      'Glass Art',
      'Textile Art',
      'Performance Art',
      'Land Art',
    ],
  },
  {
    category: 'Photography',
    disciplines: [
      'Photography',
      'Architecture Photography',
      'Documentary Photography',
      'Editorial Photography',
      'Advertising Photography',
      'Portrait Photography',
      'Fashion Photography',
      'Product Photography',
      'Still Life Photography',
      'Street Photography',
      'Fine Art Photography',
      'Landscape Photography',
      'Wildlife Photography',
      'Photojournalism',
      'Wedding Photography',
      'Event Photography',
      'Food Photography',
      'Sports Photography',
      'Travel Photography',
      'Aerial Photography',
      'Drone Photography',
      'Photo Retouching',
    ],
  },
  {
    category: 'Design',
    disciplines: [
      'Graphic Design',
      'Fashion Design',
      'Industrial Design',
      'Product Design',
      'Interior Design',
      'UX/UI Design',
      'UX Design',
      'UI Design',
      'Web Design',
      'Branding',
      'Brand Identity',
      'Packaging',
      'Editorial Design',
      'Publication Design',
      'Typography',
      'Type Design',
      'Lettering',
      'Logo Design',
      'Iconography',
      'Illustration',
      'Interaction Design',
      'Service Design',
      'Design Systems',
      'Information Design',
      'Data Visualization',
      'Environmental Design',
      'Wayfinding',
      'Exhibition Design',
      'Furniture Design',
      'Toy Design',
      'Jewelry Design',
      'Footwear Design',
      'Textile Design',
      'Pattern-making',
      'Surface Design',
      'Styling',
      'Art Direction',
      'Creative Direction',
      'Game Design',
    ],
  },
  {
    category: 'Audiovisual',
    disciplines: [
      'Cinematography',
      'Film',
      'Filmmaking',
      'Filmmaker',
      'Directing',
      'Screenwriting',
      'Video Editing',
      'Color Grading',
      'Motion Design',
      'Motion Graphics',
      'Animation',
      '2D Animation',
      '3D Animation',
      'Character Animation',
      'VFX',
      'Compositing',
      '3D Modeling',
      '3D Artist',
      'Concept Art',
      'Storyboarding',
      'Projection Mapping',
      'Sound Design',
      'Music Production',
      'Audio Engineering',
      'Video Production',
      'Documentary Film',
      'Commercial Film',
      'Music Video',
      'Broadcast Design',
    ],
  },
  {
    category: 'Architecture',
    disciplines: [
      'Architecture',
      'Architectural Visualization',
      'Interior Architecture',
      'Residential Architecture',
      'Commercial Architecture',
      'Public Architecture',
      'Landscape Architecture',
      'Urban Design',
      'Urban Planning',
      'Sustainable Architecture',
      'Heritage Restoration',
      'Parametric Design',
      'BIM Modeling',
    ],
  },
  {
    category: 'Cross-disciplinary',
    disciplines: [
      'Game Art',
      'Character Design',
      'Comic Art',
      'Tattoo Design',
      'Costume Design',
      'Hair & Makeup',
      'Set Design',
      'Scenography',
      'Floral Design',
      'Creative Coding',
      'Generative Art',
      'AR/VR Design',
      '3D Design',
      'Copywriting',
      'Content Design',
    ],
  },
];

/* Flat list of every discipline, in category order — backs the search box. */
export const DISCIPLINES: string[] = DISCIPLINE_CATEGORIES.flatMap(
  c => c.disciplines,
);

/* Curated set shown as pills before the user searches. */
export const SUGGESTED_DISCIPLINES: string[] = [
  '3D Artist',
  'Graphic Design',
  'VFX',
  'Photography',
  'Fashion Design',
  'Video Editing',
  'Branding',
  'Styling',
  'UX/UI Design',
  'Interior Design',
  'Filmmaker',
  'Packaging',
  'Art Direction',
  'Motion Design',
  'Creative Direction',
  'Animation',
  'Pattern-making',
];
